### ISSUE TITLE
Pega 8.1 compatible 

### ISSUE THREAD

**Issue by yokodev** [pegasystems/docker-pega7-tomcat-ready#16]
### Is this compatible with Pega 8.1 ?
I'm trying to use  [This method ](https://community1.pega.com/community/pega-support/question/how-run-pega-74-docker)  for Pega 8.1

**Comment by viper0131** [comment]
I use it as a base for 8.1 without problems.
(I remove sma related stuff)

I have I fork available on git, image can be found:
nlmacamp/docker-pega7-tomcat-ready:pega81

**Comment by yokodev** [comment]
Thanks I appreciated, I had to make my own version...  
Actually there is a [good PR](https://github.com/pegasystems/docker-pega7-tomcat-ready/pull/12). I took [some ideas](https://github.com/pegasystems/docker-pega7-tomcat-ready/pull/12/commits) from it

**Comment by viper0131** [comment]
yes, I recognize them :-)

**Comment by yokodev** [comment]
> yes, I recognize them :-)

**Phenomenal Job Thanks**

**Comment by yokodev** [comment]
@viper0131   I'm having trouble running more than **one pair** of containers.  
Pega just goes crazy, odd errors/ behaviors... 
Any thoughts on this ?

**Comment by viper0131** [comment]
Can you share the kind of errors?
Currently I run an environment with 3 containers based on this setup.

Sometimes hazelcast is a little confused when one of the nodes restarts, but otherwise everything should run file.

**Comment by yokodev** [comment]
Every tuple is in its own network... 
Then I startup the each tuple like so, each in a different network and pointing dbPort to whatever port is assigned during startup of the DB
```bash
docker run --rm --name pega8db_01 -p :5432 -e POSTGRES_USER=pega -e POSTGRES_PASSWORD=pegasys --network=pega01 pega8db:latest
docker run --rm -it -p 8085:8080 -P -e DB_HOST=pega8db_01 -e dbPort=32853 --network=pega01 --name tomcat8-01 bare-tomcat8:latest
```
Then I try in the browser  

http://**10.190.8.190:8085**/prweb/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD
http://**10.190.8.190:8086**/prweb/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD  

I start getting flickering errors on one or both of the instances, Pega would go right out to the Login Screen.... 
and I get this : 
![errorpega](https://user-images.githubusercontent.com/17376780/52216707-7b2a9000-285c-11e9-8c79-5736e066da4c.png)

Now if I change it to a name like localhost instead of the IP  

http://**10.190.8.190**:8085/prweb/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD
http://**localhost**:8086/prweb/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD 

it seems to work, 

I have not tried with more tuples cause of the resources

**Comment by yokodev** [comment]
I was able to fix the issue by putting a reverse proxy in front of them and placing each container in a different port, and it worked. Well, it's a little bit more: Domain, A records a little tweak here or there... but essentially that's it.
