### ISSUE TITLE
Validation query works for Postgres but not for Oracle

### ISSUE THREAD

**Issue by ajafoufi** [pegasystems/docker-pega7-tomcat-ready#5]
Since the validation query validationQuery="SELECT 1" works only for Postgres and not for Oracle, the PR Web application container will fail to start with the error: Failed to validate a newly established connection.

The validation query is hardcoded in docker-pega7-tomcat-ready/conf/Catalina/localhost/prweb.xml

**Comment by MaxLans** [comment]
@ajafoufi Maybe it is an idea to make an hybrid docker-pega7-tomcat-ready container. Based on the configuration you choose, that might be an variable saying: Oracle or PostgreSQL it will fill up the validation query as well as the JDBC prefix as mentioned during your other issue.

**Comment by ajafoufi** [comment]
I have made the changes locally which I could contribute.

**Comment by MaxLans** [comment]
Hi @ajafoufi, great job. Will check.

**Comment by dcasavant** [comment]
@ajafoufi Please feel free to submit a pull request.  It will be reviewed accordingly.

**Comment by ajafoufi** [comment]
@dcasavant  The pull request is already submitted on June, 20.
