### ISSUE TITLE
PostgreSQL Running?

### ISSUE THREAD

**Issue by zdharmawan** [pegasystems/docker-pega7-tomcat-ready#7]
Hi all,

Does this Docker image has PostgreSQL already running. I couldn't manage to get it up and running? Sorry for such newbie question.

Regards,
Zul

**Comment by cdancy** [comment]
@zdharmawan this is a tomcat image and does NOT have postgres. The docker standard is to map a single application to a single image. 

If you're looking for a postgres image [you can find that here](https://github.com/pegasystems/postgres-pljava-openjdk).
